# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DAQGUI.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DAQWindow(object):
    def setupUi(self, DAQWindow):
        DAQWindow.setObjectName(_fromUtf8("DAQWindow"))
        DAQWindow.resize(1153, 968)
        self.centralwidget = QtGui.QWidget(DAQWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.DescriptionEdit = QtGui.QPlainTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.DescriptionEdit.setFont(font)
        self.DescriptionEdit.setObjectName(_fromUtf8("DescriptionEdit"))
        self.gridLayout.addWidget(self.DescriptionEdit, 8, 1, 1, 4)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.scriptLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.scriptLineEdit.setObjectName(_fromUtf8("scriptLineEdit"))
        self.horizontalLayout_2.addWidget(self.scriptLineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.custDAQTextBrowser = QtGui.QTextBrowser(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.custDAQTextBrowser.setFont(font)
        self.custDAQTextBrowser.setObjectName(_fromUtf8("custDAQTextBrowser"))
        self.verticalLayout_2.addWidget(self.custDAQTextBrowser)
        self.gridLayout.addLayout(self.verticalLayout_2, 8, 0, 1, 1)
        self.cutomCheckBox = QtGui.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cutomCheckBox.setFont(font)
        self.cutomCheckBox.setStyleSheet(_fromUtf8("QCheckBox::indicator { width:30px; height: 30px; }"))
        self.cutomCheckBox.setObjectName(_fromUtf8("cutomCheckBox"))
        self.gridLayout.addWidget(self.cutomCheckBox, 7, 0, 1, 1)
        self.DescriptionLabel = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.DescriptionLabel.setFont(font)
        self.DescriptionLabel.setObjectName(_fromUtf8("DescriptionLabel"))
        self.gridLayout.addWidget(self.DescriptionLabel, 7, 1, 1, 3)
        self.DAQlabel = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(34)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.DAQlabel.setFont(font)
        self.DAQlabel.setObjectName(_fromUtf8("DAQlabel"))
        self.gridLayout.addWidget(self.DAQlabel, 2, 1, 1, 1)
        self.addButton = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.addButton.setFont(font)
        self.addButton.setObjectName(_fromUtf8("addButton"))
        self.gridLayout.addWidget(self.addButton, 5, 1, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.PassDAQCheckBox = QtGui.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.PassDAQCheckBox.setFont(font)
        self.PassDAQCheckBox.setStyleSheet(_fromUtf8("QCheckBox::indicator { width:30px; height: 30px; }"))
        self.PassDAQCheckBox.setChecked(True)
        self.PassDAQCheckBox.setObjectName(_fromUtf8("PassDAQCheckBox"))
        self.verticalLayout.addWidget(self.PassDAQCheckBox)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.nShotsLabel = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.nShotsLabel.setFont(font)
        self.nShotsLabel.setObjectName(_fromUtf8("nShotsLabel"))
        self.horizontalLayout.addWidget(self.nShotsLabel)
        self.nShotsLineEdit = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nShotsLineEdit.sizePolicy().hasHeightForWidth())
        self.nShotsLineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.nShotsLineEdit.setFont(font)
        self.nShotsLineEdit.setObjectName(_fromUtf8("nShotsLineEdit"))
        self.horizontalLayout.addWidget(self.nShotsLineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.PassDAQTextBrowser = QtGui.QTextBrowser(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.PassDAQTextBrowser.setFont(font)
        self.PassDAQTextBrowser.setObjectName(_fromUtf8("PassDAQTextBrowser"))
        self.verticalLayout.addWidget(self.PassDAQTextBrowser)
        self.gridLayout.addLayout(self.verticalLayout, 3, 0, 2, 1)
        self.refreshListButton = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.refreshListButton.setFont(font)
        self.refreshListButton.setObjectName(_fromUtf8("refreshListButton"))
        self.gridLayout.addWidget(self.refreshListButton, 6, 1, 1, 1)
        self.removeButton = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.removeButton.setFont(font)
        self.removeButton.setObjectName(_fromUtf8("removeButton"))
        self.gridLayout.addWidget(self.removeButton, 5, 2, 1, 3)
        self.liveViewButton = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.liveViewButton.setFont(font)
        self.liveViewButton.setObjectName(_fromUtf8("liveViewButton"))
        self.gridLayout.addWidget(self.liveViewButton, 6, 2, 1, 3)
        self.SelectedLabel = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.SelectedLabel.setFont(font)
        self.SelectedLabel.setObjectName(_fromUtf8("SelectedLabel"))
        self.gridLayout.addWidget(self.SelectedLabel, 3, 2, 1, 3)
        self.AvailableLabel = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.AvailableLabel.setFont(font)
        self.AvailableLabel.setObjectName(_fromUtf8("AvailableLabel"))
        self.gridLayout.addWidget(self.AvailableLabel, 3, 1, 1, 1)
        self.availableListWidget = QtGui.QListWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.availableListWidget.setFont(font)
        self.availableListWidget.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.availableListWidget.setObjectName(_fromUtf8("availableListWidget"))
        self.gridLayout.addWidget(self.availableListWidget, 4, 1, 1, 1)
        self.selectedListWidget = QtGui.QListWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.selectedListWidget.setFont(font)
        self.selectedListWidget.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.selectedListWidget.setObjectName(_fromUtf8("selectedListWidget"))
        self.gridLayout.addWidget(self.selectedListWidget, 4, 2, 1, 1)
        self.startDAQButton = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.startDAQButton.setFont(font)
        self.startDAQButton.setAutoFillBackground(False)
        self.startDAQButton.setStyleSheet(_fromUtf8("background-color: rgb(0, 170, 0);\n"
"color:white;"))
        self.startDAQButton.setObjectName(_fromUtf8("startDAQButton"))
        self.gridLayout.addWidget(self.startDAQButton, 9, 1, 1, 1)
        self.abortDAQButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.abortDAQButton.sizePolicy().hasHeightForWidth())
        self.abortDAQButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.abortDAQButton.setFont(font)
        self.abortDAQButton.setStyleSheet(_fromUtf8("background-color: rgb(255, 0, 0);\n"
"color:white;"))
        self.abortDAQButton.setObjectName(_fromUtf8("abortDAQButton"))
        self.gridLayout.addWidget(self.abortDAQButton, 9, 0, 1, 1)
        self.DAQProgress = QtGui.QProgressBar(self.centralwidget)
        self.DAQProgress.setMaximum(100)
        self.DAQProgress.setProperty("value", 0)
        self.DAQProgress.setObjectName(_fromUtf8("DAQProgress"))
        self.gridLayout.addWidget(self.DAQProgress, 9, 2, 1, 1)
        DAQWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(DAQWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1153, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        DAQWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(DAQWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        DAQWindow.setStatusBar(self.statusbar)

        self.retranslateUi(DAQWindow)
        QtCore.QObject.connect(self.abortDAQButton, QtCore.SIGNAL(_fromUtf8("clicked()")), DAQWindow.close)
        QtCore.QObject.connect(self.addButton, QtCore.SIGNAL(_fromUtf8("clicked()")), DAQWindow.addFunction)
        QtCore.QObject.connect(self.refreshListButton, QtCore.SIGNAL(_fromUtf8("clicked()")), DAQWindow.refreshListFunc)
        QtCore.QObject.connect(self.removeButton, QtCore.SIGNAL(_fromUtf8("clicked()")), DAQWindow.removeFunction)
        QtCore.QObject.connect(self.liveViewButton, QtCore.SIGNAL(_fromUtf8("clicked()")), DAQWindow.liveViewFunc)
        QtCore.QObject.connect(self.startDAQButton, QtCore.SIGNAL(_fromUtf8("clicked()")), DAQWindow.startDAQFunc)
        QtCore.QMetaObject.connectSlotsByName(DAQWindow)

    def retranslateUi(self, DAQWindow):
        DAQWindow.setWindowTitle(_translate("DAQWindow", "DAQ GUI", None))
        self.DescriptionEdit.setPlainText(_translate("DAQWindow", "This dataset is just a test. Laser is off; no plasma. Recording 100 shots.", None))
        self.label.setText(_translate("DAQWindow", "Script Name:", None))
        self.scriptLineEdit.setText(_translate("DAQWindow", "customScript.py", None))
        self.custDAQTextBrowser.setHtml(_translate("DAQWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:18pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Custom Script Output:</p></body></html>", None))
        self.cutomCheckBox.setText(_translate("DAQWindow", "Custom Script", None))
        self.DescriptionLabel.setText(_translate("DAQWindow", "Dataset Description:", None))
        self.DAQlabel.setText(_translate("DAQWindow", "CU-PWFA DAQ", None))
        self.addButton.setText(_translate("DAQWindow", "Add Device(s)", None))
        self.PassDAQCheckBox.setText(_translate("DAQWindow", "Passive DAQ", None))
        self.nShotsLabel.setText(_translate("DAQWindow", "Number of Shots:", None))
        self.nShotsLineEdit.setText(_translate("DAQWindow", "100", None))
        self.PassDAQTextBrowser.setHtml(_translate("DAQWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:18pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Passive DAQ Output:</p></body></html>", None))
        self.refreshListButton.setText(_translate("DAQWindow", "Get List", None))
        self.removeButton.setText(_translate("DAQWindow", "Remove Device(s)", None))
        self.liveViewButton.setText(_translate("DAQWindow", "Live View (Single Camera)", None))
        self.SelectedLabel.setText(_translate("DAQWindow", "Selected Instruments:", None))
        self.AvailableLabel.setText(_translate("DAQWindow", "Available Instruments:", None))
        self.startDAQButton.setText(_translate("DAQWindow", "START DAQ", None))
        self.abortDAQButton.setText(_translate("DAQWindow", "ABORT DAQ", None))

